### ISSUE TITLE
gsd fl module docs are out of date

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/gsd#116]
## Description

The examples in the docs show the `write_chunk` method has 3 arguments, where it should only take two arguments.

## Developer

Anyone who contributes do gsd could do the fix.

**Comment by joaander** [comment]
@tommy-waltmann Which example specifically has the problem? Can you provide a link, screenshot, or better yet a github link to the line of code? 

The examples here look fine: https://gsd.readthedocs.io/en/stable/python-module-gsd.fl.html#gsd.fl.GSDFile.write_chunk

To avoid errors like this, GSD configures sphinx to execute the example code as it builds the documentation and show the output. If any of these executed examples had an incorrect number of arguments, the documentation build would fail.

**Comment by tommy-waltmann** [comment]
I believe I confused the second argument of `np.array` for a third argument to `write_chunk`. Everything is fine.
