### ISSUE TITLE
GSD C API cannot fully handle file paths containing non-English characters on Windows platform

### ISSUE THREAD

**Issue by stukowski** [glotzerlab/gsd#136]
Consider a file path such as `C:\中文\test.gsd` on Windows containing non-ANSI characters. The current implementation of [gsd_open()](https://gsd.readthedocs.io/en/stable/c-api.html#c.gsd_open) cannot handle such paths very well, because it relies on the POSIX `open()` function ([_open()](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen?view=msvc-170) on Windows). _open() takes a `const char*` string, which must use the current system code page of Windows. If that code page is set to English ([Windows-1252](https://en.wikipedia.org/wiki/Windows-1252)), for example, the Chinese characters cannot be represented and the file operation fails (or even leads to a program crash, see below).

Unix/Linux platforms use the UTF-8 encoding for filenames, which supports the complete Unicode charset. But this is not the case on Windows. Here, the better approach is to use the [_wopen()](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen?view=msvc-170) function, which accepts a wide-character string and is independent of the system's active code page. 

Apparently, other cross-platform I/O libraries such as HDF5 also made the choice of using `_open()` on Windows, and have been [plagued by its deficiencies by more than a decade](https://forum.hdfgroup.org/t/non-english-characters-in-hdf5-file-name/4627/4). That's why I suggest for GSD to switch to `_wopen()` if possible. Of course, this means also changing the signature of `gsd_open()` and other functions to accept file paths as `const wchar_t*` (on Windows only). One option would be to provide a separate overload such as `gsd_wopen()` to not break existing applications.

We became aware of the problem of the existing `gsd_open()` implementation when OVITO users reported a program crash when attempting to open file paths containing non-English characters:

https://www.ovito.org/forum/topic/ovito-3-7-3-does-not-open-certain-types-of-files-if-their-path-contains-cjk-characters/

OVITO uses UTF-16 encoded file paths internally (Qt framework) and was converting them to UTF-8 for the call to `gsd_open()`. This leads to a program crash, because `_open()` expects the use of the system's locale code page. But if that code page cannot represent all the characters in the original file path, the file cannot be opened. As an interims solution we worked around the problem by [patching the GSD functions](https://gitlab.com/stuko/ovito/-/commit/db87e26b0184be02e6490c1330ea286d3a9489c1#3b7cb6dae78979e637776f82099124dafb3614c7) in the downstream project.

**Comment by stukowski** [comment]
Let me propose another possible solution, which would leave the public C API of GSD unchanged:

Currently, `gsd_open()` takes the filename as a `const char*` but the documentation leaves the encoding to be used for the string parameter undefined. One could make this more explicit and specify UTF-8 as the encoding on all platforms. On Linux/Unix this leads to no change, because UTF-8 is the standard anyway. On Windows, the implementation of `gsd_open()` will have to convert the UTF-8 string to UTF-16 before it can be passed to [_wopen()](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen?view=msvc-170). The conversion can easily be done using the [MultiByteToWideChar()](https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar) function, I think.

I could work on this and make a pull request if you agree.

**Comment by joaander** [comment]
Thanks for the bug report. I added a test in #137 that confirms the incorrect behavior.

I like your second idea to use `MultiByteToWideChar` and define the encoding of `fname` in the API. We'll need to add it in `gsd_open`, `gsd_create`, and `gsd_create_and_open`. All of these functions already have an `#ifdef _WIN32` block for Windows specific code. Please go ahead and make a pull request.

**Comment by stukowski** [comment]
By the way, I noticed that this problem typically occurs only on Windows 7/8/10 systems but not on Windows 11. That's because Microsoft has activated the option ["Beta: Use Unicode UTF-8 for worldwide language support"](https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do) in the system settings on Windows 11 by default. This expert option makes the `_open()` system function accept UTF-8 encoded paths.

**Comment by joaander** [comment]
Thanks, that is good to know. If I understand correctly, the fix using `_wopen` should work on Windows 11 and older versions.

**Comment by stukowski** [comment]
Yes, using `_wopen` is the safest approach and also recommended by Microsoft. It works on all Windows versions and ensures that the behaviour is independent of the user's system language & code page settings.
