### ISSUE TITLE
gsd.hoomd.open can't load the film

### ISSUE THREAD

**Issue by insung1127** [glotzerlab/gsd#25]
Hello,

I'm trying to use the gsd.hoomd in Windows 10 but have been experiencing the following problem. I think I installed the gsd module correctly but can't use gsd.hoomd.open. The error message was "file layer module is not available". Can anyone please give me some advice if you have had this problem before?

![image](https://user-images.githubusercontent.com/25071059/57986596-d0259700-7a44-11e9-99f0-de76111cc7b7.png)

Thanks,
Insung Han

**Comment by joaander** [comment]
This error message indicates that the `gsd` cython module was not compiled and installed. I do not support gsd on windows. You might have luck with the pure python `pygsd` module: https://gsd.readthedocs.io/en/stable/python-module-gsd.pygsd.html

**Comment by insung1127** [comment]
Hello Joshua,

Unfortunately, the pygsd module did not work. Instead, I also tried the
same code (gsd.hoomd) in Linux and found a different error.

Would you be able to have a look at this problem? Thank you very much!

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
runfile('/media/insungh/HD-LXU3/QCmerging/quasicrystal_viz.py',
wdir='/media/insungh/HD-LXU3/QCmerging')
  0%|          | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):

  File "<ipython-input-5-f732af5a1290>", line 1, in <module>
    runfile('/media/insungh/HD-LXU3/QCmerging/quasicrystal_viz.py',
wdir='/media/insungh/HD-LXU3/QCmerging')

  File
"/home/insungh/Desktop/Anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py",
line 786, in runfile
    execfile(filename, namespace)

  File
"/home/insungh/Desktop/Anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py",
line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/media/insungh/HD-LXU3/QCmerging/quasicrystal_viz.py", line 26, in
<module>
    boxes.append(frame.box)

AttributeError: 'Snapshot' object has no attribute 'box'
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Best,
Insung

**Comment by joaander** [comment]
This is not a bug, the error message is correct: the `Snapshot` object has no attribute `box`. Try `frame.configuration.box`.

github issues are for feature requests and bug reports. Please ask technical support questions on the [hoomd-users mailing list](https://groups.google.com/d/forum/hoomd-users) where a large community of users is available to help.
