### ISSUE TITLE
Add `HOOMDTrajectory.flush()`.

### ISSUE THREAD

**Issue by joaander** [glotzerlab/gsd#259]
### Description

Add a `flush` method to `HOOMDTrajectory`.

### Proposed solution

```
f = gsd.hoomd.open('trajectory', 'w')
f.flush()
```

### Additional context

Users expect to be able to flush writes on objects opened with `open`.

**Comment by Harshal662** [comment]
class HOOMDTrajectory:
    # existing code
    
    def flush(self):
        # Code to flush writes
        pass
        
I think by adding this it would be able to flush writes on objects opened with open.

**Comment by joaander** [comment]
No, `pass` does not flush, it does nothing. The method should call `flush` on the held `file` handle.
