### ISSUE TITLE
Opening existing file with mode 'x' raises OSError instead of FileExistsError indicated by documentation

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/gsd#270]
### Description

The [gsd.hoomd documentation](https://gsd.readthedocs.io/en/v3.1.0/python-module-gsd.hoomd.html#gsd.hoomd.open) says calling `gsd.hoomd.open` with mode = `x` and a filename of a file that already exists will raise a `FileExistsError`. It appears that this scenario will raise the parent `OSError` instead of the specific subclass `FileExistsError`. 

### Script

```python
import gsd.hoomd

# with-slashes.gsd already exists in the cwd
with gsd.hoomd.open('with-slashes.gsd', 'x') as f:
    pass
```

### Output

```shell
Traceback (most recent call last):
  File "/Users/tcmoore3/sandbox/test-gsd-mode-error.py", line 3, in <module>
    with gsd.hoomd.open('with-slashes.gsd', 'x') as f:
  File "/Users/tcmoore3/anaconda/lib/python3.9/site-packages/gsd/hoomd.py", line 1082, in open
    gsdfileobj = fl.open(name=str(name),
  File "gsd/fl.pyx", line 226, in gsd.fl.open
  File "gsd/fl.pyx", line 366, in gsd.fl.GSDFile.__init__
  File "gsd/fl.pyx", line 43, in gsd.fl.__raise_on_error
OSError: [Errno 9] Bad file descriptor: 'with-slashes.gsd'
```

### Expected output

A `FileExistsError` 

### Platform

Linux, macOS

### Installation method

Conda package

### GSD

3.0.1

### Python version

3.9 (macOS) and 3.11 (Linux)

**Comment by joaander** [comment]
Feel free to submit a pull request that corrects this issue. 
1. Check `fd` and `errno` after opening the file and before initializing:
https://github.com/glotzerlab/gsd/blob/73a64ede6b2de74452381cb7066b1357c11d6891/gsd/gsd.c#L1622-L1625
https://github.com/glotzerlab/gsd/blob/73a64ede6b2de74452381cb7066b1357c11d6891/gsd/gsd.c#L1667-L1670
https://github.com/glotzerlab/gsd/blob/73a64ede6b2de74452381cb7066b1357c11d6891/gsd/gsd.c#L1695-L1712

2. Convert the errno to the desired exception.
