### ISSUE TITLE
build 1.8.0 showing up for python 2.7 on conda

### ISSUE THREAD

**Issue by IAlibay** [glotzerlab/gsd#30]
## Description

Hi,

Going from glotzerlab/gsd#28 it looks like python 2.7 support got dropped in GSD 1.8.0. However, there are still python2.7 conda builds being created. I couldn't work out who maintains the conda-forge build, so apologies if I am reporting in the wrong place.

## Script

conda search gsd -c conda-forge
...
gsd                       1.8.0  py27hc1659b7_0  conda-forge         
gsd                       1.8.0  py36hc1659b7_0  conda-forge         
gsd                       1.8.0  py36hc1659b7_1  conda-forge         
gsd                       1.8.0  py37hc1659b7_0  conda-forge         
gsd                       1.8.0  py37hc1659b7_1  conda-forge  

Platform:
- Linux

Installation method:
- Conda package

Versions:
- Python version: 2.7
- **GSD** version: 1.8.0

**Comment by joaander** [comment]
I already fixed this. Note that the later `_1` builds in your list are only for py36 and py37.

**Comment by IAlibay** [comment]
Thanks, I hadn't noticed the newer builds.

As an additional question, I'm probably asking for bit much, but is there any way that the py2.7 1.8.0 conda-forge build be given a `broken` label? That way conda installs don't default to an unusable build version?

**Comment by joaander** [comment]
requested conda-forge/gsd-feedstock#21

**Comment by IAlibay** [comment]
Awesome that seems to have fixed things 😄 

Thanks so much for your help on this @joaander
