### ISSUE TITLE
v3.2.0 HTMLzip missing from gsd.readthedocs.io

### ISSUE THREAD

**Issue by rathann** [glotzerlab/gsd#303]
### Description

v3.2.0 documentation zip is missing from https://readthedocs.org/projects/gsd/downloads/

### Script

```python
wget -O gsd-v3.2.0-html.zip https://readthedocs.org/projects/gsd/downloads/htmlzip/v3.2.0/
```

### Output

```shell
--2023-11-22 12:26:24--  https://readthedocs.org/projects/gsd/downloads/htmlzip/v3.2.0/
Resolving readthedocs.org (readthedocs.org)... 104.18.6.29, 104.18.7.29, 2606:4700::6812:71d, ...
Connecting to readthedocs.org (readthedocs.org)|104.18.6.29|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-11-22 12:26:25 ERROR 404: Not Found.
```
```


### Expected output

Expecting output similar to what I get for 3.1.1:

```
--2023-11-22 12:28:13--  https://readthedocs.org/projects/gsd/downloads/htmlzip/v3.1.1/
Resolving readthedocs.org (readthedocs.org)... 104.18.7.29, 104.18.6.29, 2606:4700::6812:71d, ...
Connecting to readthedocs.org (readthedocs.org)|104.18.7.29|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 139668 (136K) [application/zip]
Saving to: ‘gsd-v3.1.1-html.zip’

gsd-v3.1.1-html.zip           100%[=================================================>] 136.39K   604KB/s    in 0.2s    

2023-11-22 12:28:14 (604 KB/s) - ‘gsd-v3.1.1-html.zip’ saved [139668/139668]
```

### Platform

Linux

### Installation method

Compiled from source

### GSD

3.2.0

### Python version

3.11.6

**Comment by joaander** [comment]
The htmlzip documentation failed to build, so I removed it: 70f7c04349646dd997ae23a3f90aecfbb6590f65

It appears that the bug may have been fixed: https://github.com/pradyunsg/furo/discussions/709. If htmlzip output is important for you, please submit a pull request to enable it.
