### ISSUE TITLE
reduced precision

### ISSUE THREAD

**Issue by EliasZirdehi** [glotzerlab/gsd#343]
### Description

I would like to suggest a new feature to the 'GSD' format which makes users able to choose a lower precision when saving the stored data. This would be useful for the vary large trajectories as the required disk space is reduced. Then the precision used when saving the trajectory could also be written in the file so that one can read it when opening it.

### Proposed solution

As far as I know, 'XTC' is the lowest-precision format. I think adding a similar level of precision makes the 'GSD' format perfect, in particular, for the biomolecular community taking advantage of hoomd-blue.

**Comment by joaander** [comment]
GSD is not XTC. Feel free to contribute a XTC writer to HOOMD-blue if you would like it to write that file format.
