### ISSUE TITLE
Add CLI entrypoint for file reading

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/gsd#72]
## Description

I frequently open and inspect GSD files in the Python interpreter for testing. It would be convenient to add some simple entry points to the Python interface to be able to do something like `read_gsd FILENAME` on the command line. This would be extremely simple, the equivalent of executing `python -i read.py`  where `read.py` is a Python script like
```python
# read.py
import gsd.hoomd
traj = gsd.hoomd.open(FILENAME)
```
but possibly with additional flags that could be added for e.g. different schema or opening directly with the file layer.

## Proposed solution

This could be implemented using Python's built-in entrypoints function for installation when using setup.py. I'm not sure if the CMake build supports this, that might require some additional changes.

## Developer

I'm happy to take this on if there's interest.

**Comment by joaander** [comment]
Sure, I'm in favor of this.

One option is to just not support this in the CMake builds. There is no `make install` target for CMake in gsd now, it exists only to prepare the module in the build directory.

**Comment by vyasr** [comment]
If we're OK with not supporting this in CMake builds then there's no problem, it's easy enough to implement.
