### ISSUE TITLE
Rewrite to a chunk

### ISSUE THREAD

**Issue by li-jintao** [glotzerlab/gsd#75]
## Description

Rewrite into an existing chunk at a specific frame.

## Proposed solution

Now users can read data of any frames, while write data can only be implemented by adding extra frames.
Since I am trying to prepress my data, which means read the data at a frame then processed and overwrite that chunk at that frame.

## Additional context

N/A

## Developer

N/A

**Comment by joaander** [comment]
Thanks for the request. We have no plans to allow modifying existing file contents at this time. `gsd` is designed as a minimal file format to capture trajectory output and does not provide the complexities necessary to allow overwriting or adding new chunks except at the current frame. If you want to save your processed data, you can write the output to a new file. If you need a file format that allows modification of existing data, check out HDF5.

**Comment by li-jintao** [comment]
Dear Joshua, 

Thanks for your prompt reply and clear clarification.
Now I understand your philosophy and sounds quite a nice idea to keep things tidy here.

Best regards,
Jintao
