### ISSUE TITLE
pip install picks up GSD 1.8.0 on py2.7

### ISSUE THREAD

**Issue by IAlibay** [glotzerlab/gsd#84]
## Description

I think this is partially related to #30 

We're doing a legacy support release for MDAnalysis and we're noticing that `pip install gsd` will pick up v1.8.0 on python 2.7. As far as I'm aware 1.8 dropped support for py2.7, causing gsd calls to fail.

This causes issues with pip-only installs. Technically we could pin the release to <1.8.0 but we'd prefer not limit users from using the newer GSD versions where possible.

Assuming you can reproduce this behaviour, I was therefore wondering if you'd be willing to yank the 1.8 release from pypi so that py2.7 didn't default to it?

## Configuration

Platform:
- Linux: ubuntu 20.04 LTS

Installation method:
- pip (pypi)

Versions:
- Python version: 2.7
- **GSD** version: 1.8.0

## Developer

Unfortunately any fix here would have to be done by the pypi maintainer.

**Comment by joaander** [comment]
I removed the 1.8.0 release on pypi.
